sudo: false
language: scala
scala:
  - 2.10.7
  - 2.11.12
  - 2.12.6
jdk:
  - oraclejdk8
env:
  - JSDOM_VERSION=9.12.0
  - JSDOM_VERSION=10.0.0
install:
  # We need a recent version of Node.js for jsdom
  - nvm install 6
  - nvm use 6
  - node --version
  # Of course we need jsdom
  - npm install jsdom@$JSDOM_VERSION
script:
  - sbt ++$TRAVIS_SCALA_VERSION scalajs-env-jsdom-nodejs/test scalajs-env-jsdom-nodejs/doc
  - |
      if [[ "${TRAVIS_SCALA_VERSION}" != "2.10.7" ]]; then
        sbt ++$TRAVIS_SCALA_VERSION test-project/run test-project/test
      fi
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
