sudo: false
language: scala
scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2
jdk:
  - oraclejdk8
env:
  - JSDOM_VERSION=9.12.0
  - JSDOM_VERSION=10.0.0
install:
  # The default ivy resolution takes way too much time, and times out Travis builds.
  # We use coursier instead.
  - mkdir -p $HOME/.sbt/0.13/plugins/
  - echo 'addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC3")' > $HOME/.sbt/0.13/plugins/coursier.sbt
  # We need a recent version of Node.js for jsdom
  - nvm install 6
  - nvm use 6
  - node --version
  # Of course we need jsdom
  - npm install jsdom@$JSDOM_VERSION
  # While there is no published version of Scala.js 1.x, we have to locally build a snapshot.
  - git clone https://github.com/scala-js/scala-js.git
  - cd scala-js
  - git checkout d25fa8bba708977c68c093fdbc50958368f9602f
  - sbt ++$TRAVIS_SCALA_VERSION compiler/publishLocal jUnitPlugin/publishLocal library/publishLocal testInterface/publishLocal jUnitRuntime/publishLocal ir/publishLocal tools/publishLocal jsEnvs/publishLocal jsEnvsTestKit/publishLocal nodeJSEnv/publishLocal
  - sbt ++2.10.6 ir/publishLocal tools/publishLocal jsEnvs/publishLocal nodeJSEnv/publishLocal testAdapter/publishLocal sbtPlugin/publishLocal
  - cd ..
script:
  - sbt ++$TRAVIS_SCALA_VERSION scalajs-env-jsdom-nodejs/test scalajs-env-jsdom-nodejs/doc
  - sbt ++$TRAVIS_SCALA_VERSION test-project/run test-project/test
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
  - rm $HOME/.sbt/0.13/plugins/coursier.sbt
